name: Process Figma Tokens PR

on: pull-request

jobs: 
  run_if:
    if: ${{github.head_ref== 'design/tokens'}}
    name: Process Figma Tokens
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps: 
      -uses: actions/checkout@main
        with:
          repository: ${{github.event.pull_request.head.repo.full_name}}
          ref: ${{github.event.pull_request.head.ref}}

      -name: Install Dependencies
        run: npm install

      -name: Run token-transformer
      run: npx token-transformer sd-input/src/figma-tokens-output.json sd-input/src/sd-input.json --resolveRefernce false --expandTypography

      -name: Run style-dictionary
        run: npx style-dictionary build --config sd.config.cjs

      -name: Commit changes
       uses: EndBug/add-and-commit@v9
       with: 
        author_name: khaled
        author_email: khaledabou1985@gmail.com
        message: 'chore: style-dictionary output'
        add: '.'