name: Create Figma Tokens PR

on:
  push:
    branches:
      - design/tokens

jobs:
 repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "demo-tokens"
        source_branch: "design/tokens"
        destination_branch: "main"
        pr_title: "Figma Tokens Update"
        pr_body: "Design tokens were updated in Figma! This PR was created to update the code"
        github_token: ${{secrets.GH_PAT}}